/**
 * Bounded sequences of the change-lifecycle model's actions, generated by fast-check under the model's own
 * preconditions and replayed on the kernel, which must follow the model and keep its properties after each
 * step. A random campaign samples the sequences; it claims no exhaustivity, which is TLC's.
 */
import { strict as assert } from "node:assert";
import { existsSync, readFileSync, statSync } from "node:fs";
import { resolve } from "node:path";
import { describe, it } from "node:test";
import { decide } from "../../src/domain/change/decide.ts";
import {
	assertCampaignHolds,
	type CampaignOptions,
	REDUCED_CASES,
	readReducedCase,
	runCampaign,
	sampleActions,
} from "../support/change-commands.ts";
import type { Decider } from "../support/kernel-replay.ts";

/** The injected defect: the kernel records a result whatever protocol revision it ran under. */
const revisionGuardDropped: Decider = (state, command, policy) => {
	const frozen = state?.protocol?.ref;
	if (command.type !== "verification.record" || frozen === undefined) return decide(state, command, policy);
	const evidence = command.evidence.map((e) => ({
		...e,
		protocol_id: frozen.protocol_id,
		protocol_revision: frozen.revision,
	}));
	return decide(state, { ...command, evidence }, policy);
};

const installedFastCheck = (
	JSON.parse(readFileSync("node_modules/fast-check/package.json", "utf8")) as { version: string }
).version;
const modelDigest = (
	JSON.parse(readFileSync("specs/formal/change-lifecycle/manifest.json", "utf8")) as { files: Record<string, string> }
).files["ChangeLifecycle.tla"];

/** Runs a campaign that finds a gap, and returns its failure message and the file it names as the kept reduced case. */
function gapOf(o: CampaignOptions, defect: string): { file: string; message: string } {
	try {
		assertCampaignHolds(o, defect);
	} catch (error) {
		const message = error instanceof Error ? error.message : String(error);
		const file = /(test-output\/formal-traces\/reduced\/\S+\.json)/.exec(message)?.[1];
		if (file) return { file, message };
		throw new Error("the campaign's failure names no file of test-output/formal-traces/reduced/", { cause: error });
	}
	assert.fail("the campaign finds the gap");
}

describe("generated change-lifecycle sequences on the kernel", () => {
	it("une graine rejouée produit les mêmes actions et un défaut injecté est réduit en séquence conservée", () => {
		const first = sampleActions(495, 20);
		assert.ok(
			first.some((actions) => actions.length > 0),
			"a seed yields generated actions",
		);
		assert.deepEqual(sampleActions(495, 20), first, "a seed replayed yields the same actions");

		const { file } = gapOf(
			{ seed: 495, numRuns: 300, decide: revisionGuardDropped },
			"the kernel records a result of an earlier protocol revision",
		);
		const kept = readReducedCase(file);
		assert.equal(kept.seed, 495);
		assert.match(kept.path, /^\d+(:\d+)+$/, "the path kept runs from the failing run through its reductions");
		assert.deepEqual(kept.versions, {
			"fast-check": installedFastCheck,
			node: process.version,
			model: modelDigest,
			trace_format: 1,
		});
		assert.ok(kept.sequence.length > 0 && kept.sequence.length <= 8, `a minimal sequence: ${kept.sequence.join(", ")}`);
		assert.match(kept.sequence.at(-1) ?? "", /^Deliver/, "the sequence ends on the result the defect records");
		assert.match(kept.failure, /step \d+ Deliver/);

		const replay = { seed: kept.seed, path: kept.path, replayPath: kept.replay_path, decide: revisionGuardDropped };
		const replayed = runCampaign({ ...replay, reduce: false });
		assert.deepEqual(
			replayed.sequence,
			kept.sequence,
			"the kept seed and path replay the reduced sequence as it stands",
		);
		assert.equal(runCampaign(replay).path, kept.path, "fast-check reduces the kept sequence no further: it is minimal");
	});

	it("the archived reduced case replays to its kept sequence with the defect, and passes on the kernel", () => {
		const kept = readReducedCase("test/fixtures/formal-traces/reduced/revision-guard-dropped.json");
		const replay = { seed: kept.seed, path: kept.path, replayPath: kept.replay_path, reduce: false };
		const replayed = runCampaign({ ...replay, decide: revisionGuardDropped });
		assert.deepEqual(
			replayed.sequence,
			kept.sequence,
			`fast-check ${installedFastCheck} replays the case kept under fast-check ${kept.versions["fast-check"]}`,
		);
		assert.equal(replayed.failure, kept.failure);
		assert.equal(runCampaign(replay).failed, false, "the kernel itself keeps the guard the defect drops");
	});

	it("un écart trouvé sur le noyau laisse son cas réduit dans un fichier que le message d’échec nomme et qui rejoue la même séquence minimale", async (t) => {
		const defect = "the kernel records a result of an earlier protocol revision";
		const start = Date.now();
		let file = "";
		let message = "";
		await t.test("the campaign finds the gap", () => {
			({ file, message } = gapOf({ seed: 495, numRuns: 300, decide: revisionGuardDropped }, defect));
		});
		assert.ok(existsSync(file), `${file} stays after the end of the test that wrote it`);
		assert.ok(statSync(file).mtimeMs >= start, `${file} is written by this campaign, not left by an earlier one`);
		const kept = readReducedCase(file);
		assert.equal(
			resolve(file),
			resolve(REDUCED_CASES, `seed-${kept.seed}-path-${kept.path.replaceAll(":", "_")}.json`),
			"the file is named by its seed and its path",
		);
		assert.equal(kept.defect, defect);
		assert.equal(kept.seed, 495);
		assert.match(kept.path, /^\d+(:\d+)+$/);
		assert.ok(kept.replay_path, "the file carries the replay path");
		assert.deepEqual(kept.versions, {
			"fast-check": installedFastCheck,
			node: process.version,
			model: modelDigest,
			trace_format: 1,
		});
		assert.ok(kept.sequence.length > 0, "the file carries the minimal sequence");

		const replay = {
			seed: kept.seed,
			path: kept.path,
			replayPath: kept.replay_path,
			reduce: false,
			decide: revisionGuardDropped,
		};
		assert.deepEqual(
			runCampaign(replay).sequence,
			kept.sequence,
			"replayed from the file, the case yields the same minimal sequence",
		);
		assert.equal(gapOf(replay, kept.defect).message, message, "and the same failure message");
	});

	it("the kernel follows the model and keeps its properties along 3000 generated sequences", () => {
		assertCampaignHolds({ seed: 4950, numRuns: 3000 }, "the kernel departs from the model");
	});
});
